title: VideoSRS
email: videoSRS@anett-hoppe.net
description: Assisting the remote video learner with self-regulation support
author: "VideoSRS"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://videoSRS.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  videoSRS

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/progress/page:num/"
# remote-theme: minimal-mistakes-jekyll
#theme: chulapa-jekyll
remote_theme: dieghernan/chulapa

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-gist
  - jekyll-scholar
  - jekyll-relative-links
  - jekyll-remote-theme
relative-links:
  enabled: true
  collections: true
include:
  - README.md
  - test.md
